on:
  push:
    branches: [ dev ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        env:
          EC2_PUBLIC_IP: your-ec2-public-ip
          LOCAL_PORT: your-local-port
          CONTAINER_PORT: your-container-port
        run: |
          # Save SSH key to a file and set the right permissions
          echo "${{ secrets.EC2_SSH_KEY }}" > ec2_ssh_key.pem
          chmod 600 ec2_ssh_key.pem

          # Run the deployment script
          ./path/to/deploy-to-ec2.sh ec2_ssh_key.pem
